version: "3.8"

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    volumes:
      - n8n_storage:/home/node/.n8n
    networks:
      - n8n_network

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    command: "http n8n:5678"
    ports:
      - "4040:4040" # ngrok web interface
    environment:
      - NGROK_AUTHTOKEN=you_ngrok_authtoken_here
    depends_on:
      - n8n
    networks:
      - n8n_network

networks:
  n8n_network:
    driver: bridge

volumes:
  n8n_storage: